// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueuedTurnStatus } from "./QueuedTurnStatus";
import type { TurnSubmission } from "./TurnSubmission";

export type QueuedTurn = { id: string, submission: TurnSubmission, status: QueuedTurnStatus, };
