// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { UserInput } from "./UserInput";

export type TurnSubmission = {input: Array<UserInput>, /**
 * Optional JSON Schema used to constrain the final assistant message for
 * this turn.
 */
outputSchema: JsonValue | null};
